---
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

##
# Environment variables:
#   GPG_FINGERPRINT
#   GPG_PRIVATE_KEY (must be base64-decoded)
##

version: 2

# https://goreleaser.com/customization/reportsizes/
report_sizes: true

retry:
  attempts: 10
  delay: 10s
  max_delay: 5m

includes:
  - from_file:
      path: .goreleaser/__variables.yml
  - from_file:
      path: .goreleaser/meta.yml
  - from_file:
      path: .goreleaser/archives.yml
  - from_file:
      path: .goreleaser/builds.yml
  - from_file:
      path: .goreleaser/changelog.yml
  - from_file:
      path: .goreleaser/checksum.yml
  # - from_file:
  #     path: .goreleaser/chocolatey.yml
  # - from_file:
  #     path: .goreleaser/container.yml
  - from_file:
      path: .goreleaser/git.yml
  - from_file:
      path: .goreleaser/mac-universal.yml
  - from_file:
      path: .goreleaser/metadata.yml
  # - from_file:
  #     path: .goreleaser/nfpm.yml
  # - from_file:
  #     path: .goreleaser/pkg.yml
  - from_file:
      path: .goreleaser/release.yml
  - from_file:
      path: .goreleaser/retries.yml
  # - from_file:
  #     path: .goreleaser/sbom.yml
  - from_file:
      path: .goreleaser/signs.yml
# - from_file:
#     path: .goreleaser/verifiable.yml
